# sonar.projectKey=fintech-app
# sonar.projectName=Fintech App
# sonar.sources=server
# sonar.tests=server/tests
# sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
# sonar.exclusions=server/node_modules/**,server/dist/**,server/build/**

sonar.projectKey=bhanuja4776_HD
sonar.organization=bhanuja4776
sonar.sources=server
sonar.tests=server/tests
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.sourceEncoding=UTF-8